from profesor import Profesor
from estudiante import Estudiante


estudiante1 = Estudiante('Juan', 'Perez', 'a@a', '123', '1', 'Ing. de Sistemas', 'UNI', '001')
estudiante2 = Estudiante('Maria', 'Gomez', 'c@c', '789', '2', 'Ing. de Sistemas', 'UNI', '002')
estudiante1.get_datos()
estudiante2.get_datos()
print('\n')
profesor1 = Profesor('Pedro', 'Garcia', 'b@b', '456', 'Ing. de Sistemas', 'UNI')
profesor1.get_datos()
print('\n')
curso1 = profesor1.crear_curso('Curso 1', 'Descripcion 1')
curso2 = profesor1.crear_curso('Curso 2', 'Descripcion 2')
print('\n')
curso1.get_datos()
curso2.get_datos()
print('\n')
estudiante1.matricular_curso(curso1)
estudiante2.matricular_curso(curso1)
estudiante1.matricular_curso(curso2)
print('\n')
print(estudiante1.get_cursos())
print(estudiante2.get_cursos())
print('\n')
print(profesor1.get_cursos())
print('\n')
curso1.get_datos()
curso2.get_datos()
print('\n')
print(curso1.get_estudiantes())
print(curso2.get_estudiantes())
print('\n')
print(curso1.get_profesor())
print(curso2.get_profesor())
print('\n')
estudiante1.ver_profesores()
print('\n')